"""Voice route handler — STT (Whisper) and TTS (gpt-4o-mini-tts) via shared OpenAI client."""

import io
from fastapi import APIRouter, UploadFile, File, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from app.services.voice_service import transcribe_audio, synthesize_speech
from app.utils.logger import get_logger

logger = get_logger(__name__)
router = APIRouter()


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------

class SpeakRequest(BaseModel):
    text: str
    voice: str = "alloy"  # alloy | echo | fable | onyx | nova | shimmer


class TranscribeResponse(BaseModel):
    transcription: str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post("/transcribe", response_model=TranscribeResponse)
async def transcribe(file: UploadFile = File(...)) -> TranscribeResponse:
    """Accepts an audio upload and returns Whisper transcription text.

    - Content-Type must start with ``audio/`` (webm, wav, mp3, m4a, ogg, …).
    - The multipart field name must be ``file``.
    """
    if not file.content_type or not file.content_type.startswith("audio/"):
        raise HTTPException(
            status_code=415,
            detail="Unsupported media type. Please upload a valid audio file (audio/*).",
        )

    filename = file.filename or "audio.webm"
    logger.info("POST /voice/transcribe | filename=%s | content_type=%s", filename, file.content_type)

    try:
        audio_bytes = await file.read()
        text = transcribe_audio(audio_bytes, filename)
        return TranscribeResponse(transcription=text)
    except Exception as exc:
        logger.error("Whisper transcription failed: %s", exc, exc_info=True)
        raise HTTPException(status_code=500, detail=f"Transcription failed: {exc}")


@router.post("/speak")
async def speak(payload: SpeakRequest) -> StreamingResponse:
    """Accepts text and streams MP3 audio generated by gpt-4o-mini-tts.

    The response is ``audio/mpeg``.  The client should buffer or stream it.
    """
    if not payload.text.strip():
        raise HTTPException(status_code=400, detail="text must not be empty.")

    # Strip markdown so the TTS model doesn't read out raw symbols
    clean_text = payload.text.replace("**", "").replace("*", "").replace("_", "").replace("`", "").replace("#", "")
    logger.info("POST /voice/speak | voice=%s | text_length=%d", payload.voice, len(clean_text))

    try:
        audio_bytes = synthesize_speech(clean_text, voice=payload.voice)
        return StreamingResponse(io.BytesIO(audio_bytes), media_type="audio/mpeg")
    except Exception as exc:
        logger.error("TTS generation failed: %s", exc, exc_info=True)
        raise HTTPException(status_code=500, detail=f"TTS generation failed: {exc}")


# ---------------------------------------------------------------------------
# Legacy alias — keep old /tts path alive so the existing useVoice.ts works
# ---------------------------------------------------------------------------

@router.post("/tts")
async def tts_legacy(payload: dict) -> StreamingResponse:
    """Legacy alias for /voice/speak — kept for backwards compatibility."""
    text = payload.get("text", "")
    if not text.strip():
        raise HTTPException(status_code=400, detail="text must not be empty.")
    clean_text = text.replace("**", "").replace("*", "").replace("_", "").replace("`", "").replace("#", "")
    try:
        audio_bytes = synthesize_speech(clean_text)
        return StreamingResponse(io.BytesIO(audio_bytes), media_type="audio/mpeg")
    except Exception as exc:
        logger.error("TTS (legacy) failed: %s", exc, exc_info=True)
        raise HTTPException(status_code=500, detail=f"TTS failed: {exc}")
